export const dropDownItems = [
    {id : 100 , title : "All Departments" },
    {id : 101 , title : "Automotive" },
    {id : 102 , title : "Baby" },
    {id : 103 , title : "Beauty & Personal Care" },
    {id : 104 , title : "Books" },
    {id : 105 , title : "Boys' Fashion" },
    {id : 106 , title : "Copmuters" },
    {id : 107 , title : "Deals" },
    {id : 108 , title : "Digital Music" },
    {id : 109 , title : "Electronics" },
    {id : 110 , title : "Girls' Fashion" },
    {id : 111 , title : "Health & Household" },
    {id : 112 , title : "Home & Kitchen" },
    {id : 113 , title : "Industrial & Scientific" },
    {id : 114 , title : "Kinle Store" },
    {id : 115 , title : "Luggage" },
    {id : 116 , title : "Mens' Fashion" },
    {id : 117 , title : "Movies & TV" },
    {id : 118 , title : "Music , CDs & Vinyl" },
    {id : 119 , title : "Pet Supplies" },
    {id : 120 , title : "Prime Video" },
    {id : 121 , title : "Software" },
    {id : 122 , title : "Sports & Outdoors" },
    {id : 123 , title : "Tools & Home Improvement" },
    {id : 124 , title : "Toys & Games" },
    {id : 125 , title : "Video Games" },
    {id : 126 , title : "Women's Fashion" },
]
